Utkarsh/issue 186
openclimatefix/pv-site-api pull request #189
Opened 2024-09-23 18:04 UTC by Sigma-Verma

Made cache removal safer by using a lock to avoid repeated checks

# Pull Request

## Description

Enhanced thread safety by consolidating cache removal logic within a lock, preventing redundant iterations and ensuring consistent access to shared data.

## Checklist:

- [ ] My code follows [OCF's coding style guidelines](https://github.com/openclimatefix/.github/blob/main/coding_style.md)
- [ ] I have performed a self-review of my own code
- [ ] I have checked my code and corrected any misspellings

2024-09-30 07:26 UTC, peterdudfield requested changes
Thanks @Sigma-Verma for this. 

Do you mind fixing the linting, see CI?

This seems a really good way to do it, with thread locking. Do you know how this works if two calls to the api are made very close to each other? Does this then slow down the second one? Perhaps this is the only way to do it?

Perhaps there's a speed up here, where we check if these items are cache locked, and if so carry on and do nothing

2024-09-30 21:28 UTC, Sigma-Verma commented
hey can you guide me on how to fix the Linting ?
and for the question about two very close calls, 
i added a catch entry removal check
If no entries need to be removed , it will skip the locking process

2024-09-30 22:02 UTC, peterdudfield commented
> hey can you guide me on how to fix the Linting ? and for the question about two very close calls, i added a catch entry removal check If no entries need to be removed , it will skip the locking process

See errors in the github actinos and fix manually
<img width="656" alt="Screenshot 2024-09-30 at 23 01 48" src="https://github.com/user-attachments/assets/f8f87944-35e5-47d9-ab46-97c2c8fa64fd">
or do `make format`

2024-10-13 20:08 UTC, peterdudfield commented on pv_site_api/cache.py
> +        now = datetime.now(tz=timezone.utc)
is this identented correctly?

2024-10-17 06:14 UTC, peterdudfield commented
Also, do you mind incorporating #199?

2024-10-22 10:46 UTC, peterdudfield commented on pv_site_api/cache.py
> +        for key, value in last_updated.items():
could you include the .copy() that i added please

2024-10-22 10:47 UTC, peterdudfield commented
Thank you for this, just a small lint change, 

![Screenshot 2024-10-18 at 10 29 08](https://github.com/user-attachments/assets/a04b691e-558d-40cb-9452-d747c276f76e)

2024-10-28 15:08 UTC, merged